# NodeJS RESTful API Microservices
user-service1:
    build: ./user-service
    links:
        - postgres:postgres
    ports:
        - "9001:9000"
    environment:
        - "NODE_ENV=production"
user-service2:
    build: ./user-service
    links:
        - postgres:postgres
    ports:
        - "9002:9000"
    environment:
        - "NODE_ENV=production"
user-service3:
    build: ./user-service
    links:
        - postgres:postgres
    ports:
        - "9003:9000"
    environment:
        - "NODE_ENV=production"

# PostgreSQL
postgres:
    image: postgres
    ports:
        - "5432:5432"
