# Reverse Proxy
nginx:
    build: ./nginx
    links:
        - app1:app1
        - app2:app2
        - app3:app3
    ports:
        - "80:80"

# Application
app1:
    build: ./app/dist
    links:
        - postgres:postgres
    ports:
        - "9001:8080"
    environment:
        NODE_ENV: production
        SEQUELIZE_URI: "postgres://postgres:postgres@postgres/postgres"

app2:
    build: ./app/dist
    links:
        - postgres:postgres
    ports:
        - "9002:8080"
    environment:
        NODE_ENV: production
        SEQUELIZE_URI: "postgres://postgres:postgres@postgres/postgres"

app3:
    build: ./app/dist
    links:
        - postgres:postgres
    ports:
        - "9003:8080"
    environment:
        NODE_ENV: production
        SEQUELIZE_URI: "postgres://postgres:postgres@postgres/postgres"

# PostgreSQL
postgres:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: bulbthings
