# Reverse Proxy
nginx:
    build: ./nginx
    links:
        - server1:server1
        - server2:server2
        - server3:server3
    ports:
        - "80:80"

# NodeJS RESTful API
server1:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9001:9000"
    environment:
        - "NODE_ENV=production"
server2:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9002:9000"
    environment:
        - "NODE_ENV=production"
server3:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9003:9000"
    environment:
        - "NODE_ENV=production"

# PostgreSQL
postgres:
    image: postgres
    ports:
        - "5432:5432"
