# NodeJS RESTful API Microservices
server1:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9001:9000"
    environment:
        - "NODE_ENV=production"
server2:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9002:9000"
    environment:
        - "NODE_ENV=production"
server3:
    build: ./server
    links:
        - postgres:postgres
    ports:
        - "9003:9000"
    environment:
        - "NODE_ENV=production"

# PostgreSQL
postgres:
    image: postgres
    ports:
        - "5432:5432"
